server:
  port: 9090
#db configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

#Multipart configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: prod

#image upload url
project:
  image: C:\D-drive-Workspace\springbootproject\blog-app-apis\images

#debug enable
logging:
  level:
    org:
      springframework:
        security: DEBUG

